create table "public"."unique_visitor" (
    "id" bigint generated by default as identity not null,
    "url_id" bigint,
    "fingerprint" character varying not null,
    "first_visit_at" timestamp with time zone not null,
    "last_visit_at" timestamp with time zone
);


alter table "public"."unique_visitor" enable row level security;

CREATE UNIQUE INDEX unique_visitor_fingerprint_key ON public.unique_visitor USING btree (fingerprint);

CREATE UNIQUE INDEX unique_visitor_pkey ON public.unique_visitor USING btree (id);

alter table "public"."unique_visitor" add constraint "unique_visitor_pkey" PRIMARY KEY using index "unique_visitor_pkey";

alter table "public"."unique_visitor" add constraint "unique_visitor_fingerprint_key" UNIQUE using index "unique_visitor_fingerprint_key";

alter table "public"."unique_visitor" add constraint "unique_visitor_url_id_fkey" FOREIGN KEY (url_id) REFERENCES url(id) not valid;

alter table "public"."unique_visitor" validate constraint "unique_visitor_url_id_fkey";

grant delete on table "public"."unique_visitor" to "anon";

grant insert on table "public"."unique_visitor" to "anon";

grant references on table "public"."unique_visitor" to "anon";

grant select on table "public"."unique_visitor" to "anon";

grant trigger on table "public"."unique_visitor" to "anon";

grant truncate on table "public"."unique_visitor" to "anon";

grant update on table "public"."unique_visitor" to "anon";

grant delete on table "public"."unique_visitor" to "authenticated";

grant insert on table "public"."unique_visitor" to "authenticated";

grant references on table "public"."unique_visitor" to "authenticated";

grant select on table "public"."unique_visitor" to "authenticated";

grant trigger on table "public"."unique_visitor" to "authenticated";

grant truncate on table "public"."unique_visitor" to "authenticated";

grant update on table "public"."unique_visitor" to "authenticated";

grant delete on table "public"."unique_visitor" to "service_role";

grant insert on table "public"."unique_visitor" to "service_role";

grant references on table "public"."unique_visitor" to "service_role";

grant select on table "public"."unique_visitor" to "service_role";

grant trigger on table "public"."unique_visitor" to "service_role";

grant truncate on table "public"."unique_visitor" to "service_role";

grant update on table "public"."unique_visitor" to "service_role";


